[package]
org = "pramodya"
name = "package_h"
version = "2.0.0"
export = ["package_h.api.docs"]

# [[dependency]]
# org = "pramodya"
# name = "package_i"
# version = "0.1.0"
# repository="local"

[build-options]
observabilityIncluded = true